### ISSUE TITLE
Built version doesn't work

### ISSUE THREAD

**Issue by danzel** [mapbox/meta-mapbox#21]
I've tried building a yocto image for raspberry pi 3 following the instructions in the readme, I get an image but when I run `qquickmapboxgl -platform eglfs` (after setting `MAPBOX_ACCESS_TOKEN`) the UI appears but the map is grey and the machine semi locks (no mouse/keyboard input, still responds to pings).

I'm a bit new to yocto, so it's very possible I'm doing something wrong.

Any chance I could get a copy of your `bblayers.conf` and `local.conf` files @tmpsantos ?
And any other details to reproduce the build from your video would be great :-) thanks!

ATM I have done the modifications to my `local.conf`, added the raspberrypi, qt5 and mapbox layers to `bblayers.conf` and configured for raspberrypi3. (Using older qt for #20)
Then built the image using `bitbake core-image-minimal`.

**Comment by tmpsantos** [comment]
Sure, some info on the build options I used for building my image (here you can get the exact hashes I used for each layer):

```
ubuntu@yocto:~/poky/build-pi3$ bitbake -f -c compile core-image-minimal
...
Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "raspberrypi3"
DISTRO            = "poky"
DISTRO_VERSION    = "2.1"
TUNE_FEATURES     = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU        = "hard"
meta              
meta-poky         
meta-yocto-bsp    = "krogoth:898a78357e72fb80f1f8e26ba90bad5b7b054a4f"
meta-mapbox       = "master:d16f14c5934f1e106dd9c1a015792327b6d5bfa2"
meta-raspberrypi  = "master:9912d38e97671704822d1aa05312a0439cb650d3"
meta-qt5          = "krogoth:d715f2c1d340fa38f8a9860acc73de5e14a38b75"
...
```

My extra layers (the last 3 lines):

```
BBLAYERS ?= " \
  /home/ubuntu/poky/meta \
  /home/ubuntu/poky/meta-poky \
  /home/ubuntu/poky/meta-yocto-bsp \
  /home/ubuntu/tmpsantos/Projects/yocto/meta-mapbox \
  /home/ubuntu/tmpsantos/Projects/yocto/meta-raspberrypi \
  /home/ubuntu/tmpsantos/Projects/yocto/meta-qt5 \
  "
```

What I changed on the `local.conf`:

```
MACHINE ??= "raspberrypi3"

IMAGE_FSTYPES = "rpi-sdimg"
IMAGE_INSTALL_append = " qmapboxgl qt5-opengles2-test"

PACKAGECONFIG_append_pn-qtbase = " gles2 accessibility"
PACKAGECONFIG_append_pn-qmapboxgl = " gles2"
```

I was installing the Qt5 test app to test in case something goes wrong with QMapboxGL, I would have something else to try out.

But seems to me you did everything correct, so before rebuilding, try running with this environment variable set:

`QML_BAD_GUI_RENDER_LOOP=1`

There is a known bug on Qt about multithreaded GL and this env var disables that.

**Comment by danzel** [comment]
Thanks heaps!

The environmental variable didn't do it.
Will rebuild from scratch now with those settings and see how it goes.

**Comment by tmpsantos** [comment]
:+1: closing the issue, please re-open if you don't find a way to build.

**Comment by danzel** [comment]
Instructions:

```
git clone https://github.com/mapbox/meta-mapbox.git
git clone -b krogoth https://github.com/meta-qt5/meta-qt5.git
git clone -b krogoth git://git.yoctoproject.org/poky.git
git clone git://git.yoctoproject.org/meta-raspberrypi

source poky/oe-init-build-env
cd conf
nano bblayers.conf
```

Add these to the BBLAYERS list:
```
  /???/meta-mapbox \
  /???/meta-raspberrypi \
  //???/meta-qt5 \
```
(replace ??? with the absolute path)

```
nano local.conf
```

Change `MACHINE ??=` value to `raspberrypi3`
At the bottom of the file add:
```
GPU_MEM = "256"

#IMAGE_FSTYPES = "rpi-sdimg" #I didn't set this one, not required AFAICT
IMAGE_INSTALL_append = " qmapboxgl qt5-opengles2-test"

PACKAGECONFIG_append_pn-qtbase = " gles2 accessibility"
PACKAGECONFIG_append_pn-qmapboxgl = " gles2"
```

And finally
```
cd ..
bitbake core-image-minimal
```

Wait...

Write to sd card:
```
dd if=tmp/deploy/images/raspberrypi3/core-image-minimal-raspberrypi3.rpi-sdimg of=/dev/sdb && sync
```

Put the microsd card in an rpi3.

After booting:
user: root
```
export MAPBOX_ACCESS_TOKEN=...
export QML_BAD_GUI_RENDER_LOOP=1
```

Now you can run:
```
qmapboxgl -platform eglfs
or
qquickmapboxgl -platform eglfs
```

I don't get any mouse/keyboard input, but this is a start...



The first time I built this it wouldn't boot, but I did a clean and rebuild and it worked.
I get this warning during build which sounds bad:
```
WARNING: userland-git-r5 do_package_qa: QA Issue: /usr/bin/dtoverlay-post contained in package userland requires /bin/bash, but no providers found in RDEPENDS_userland? [file-rdeps]
```

My hashes:
```
meta-yocto-bsp    = "krogoth:98c57bb512ea6790db8604fcf0b88c81651d2ab4"
meta-mapbox       = "master:d16f14c5934f1e106dd9c1a015792327b6d5bfa2"
meta-raspberrypi  = "master:2745399f75d7564fcc586d0365ff73be47849d0e"
meta-qt5          = "krogoth:d715f2c1d340fa38f8a9860acc73de5e14a38b75"
```


@tmpsantos did you do anything special to get mouse/keyboard input working?
I'll google and fiddle a bit.

**Comment by tmpsantos** [comment]
> #IMAGE_FSTYPES = "rpi-sdimg" #I didn't set this one, not required AFAICT

I set this one so it builds only "rpi-sdimg" instead of all images. It is indeed not needed.

> @tmpsantos did you do anything special to get mouse/keyboard input working?
> I'll google and fiddle a bit.

My mouse worked out of the box. Not sure about the keyboard because the QML app I tried was "mouse only".

Thanks for writing this!
